version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
      - media-data:/vol/media
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
    ports:
      - "9000:9000"

  db:
    container_name: db
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    container_name: proxy
    build:
      context: ./proxy
    restart: always
    environment:
      - LISTEN_PORT=8000
      - APP_HOST=app
      - APP_PORT=9000
      - FRONTEND_PATH=/usr/share/nginx/html
    depends_on:
      - app
    ports:
      - "80:8000"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - static-data:/vol/static
      - media-data:/vol/media

volumes:
  postgres-data:
  static-data:
  media-data:
